INSERT INTO program(NAME) VALUES("BTECH");
INSERT INTO program(NAME) VALUES("BBA");
INSERT INTO program(NAME) VALUES("BCA");
insert into studentS(FIRST_NAME,SECOND_NAME,COURSE_ID) VALUES ("AARUSH","GUPTA",1) 
