INSERT INTO program(NAME) VALUES("BTECH");
INSERT INTO program(NAME) VALUES("BBA");
INSERT INTO program(NAME) VALUES("BCA");

insert into students(MOBILE,FIRST_NAME,SECOND_NAME,COURSE_ID) VALUES ("8826670530","AARUSH","GUPTA",1)

insert into rooms(BLOCK_NAME,ROOM_TYPE) VALUES ("C10","DOUBLE","FREE")

insert into rooms(BLOCK_NAME,ROOM_TYPE) VALUES ("C10","TRIPLE","FREE")


