INSERT INTO program(NAME) VALUES("BTECH");
INSERT INTO program(NAME) VALUES("BBA");
INSERT INTO program(NAME) VALUES("BCA");

insert into students(MOBILE,FIRST_NAME,SECOND_NAME,COURSE_ID) VALUES ("8826670530","AARUSH","GUPTA",1) 

